### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by SVK875** [ng2-ui/popup#11]
i have clone this project from github and setup all the required files but I am facing this error whenever i run ng serve

**TypeError: Cannot read property 'config' of null
    at Class.run (C:\Angular2\popup\node_modules\@angular\cli\tasks\serve.js:22:63)
    at check_port_1.checkPort.then.port (C:\Angular2\popup\node_modules\@angular\cli\commands\serve.js:110:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)**

i am new to angular and don't understand what to fix and how to :( !!

**Comment by allenhwkim** [comment]
Could you create a plunker example for your problem. Unless someone has the exact same problem that you have, it won't be easy to reproduce your issue without an example.

**Comment by Rathunter** [comment]
Hi @SVK875 ,

I have encountered this issue recently as well, this issue arises from your project missing the `.angular-cli.json` file in the root folder. 

This file is required for the angular-cli to work properly. However I should mention that this file is hidden and most likely did not get committed with the project.

To solve this issue I ended up contacting the project creator to send me the file. There is probably a way to reinitialize the project with angular-cli but I was not able to find how.

I hope this helps. :)
